version: '3'

services:

  hlds:
    container_name: counter-strike_server
    build: ./hokedo_server
    image: hokedo-cstrike-server
    restart: always
    environment:
      - PORT=27015
      - MAP=de_dust2
      - MAXPLAYERS=16
      - SV_LAN=0
    ports:
      - 27015:27015/udp
      - 27015:27015
    volumes:
      - ./hokedo_server/banned.cfg:/hlds/cstrike/banned.cfg
      - ./hokedo_server/listip.cfg:/hlds/cstrike/listip.cfg
      - ./hokedo_server/server.cfg:/hlds/cstrike/server.cfg
      - ./hokedo_server/mapcycle.txt:/hlds/cstrike/mapcycle.txt
      - ./hokedo_server/custom:/custom
